### ISSUE TITLE
Add travisCI badge to all READMEs.

### ISSUE THREAD

**Issue by eggshell** [BonnyCI/docs#2]
Having the badge at the top of a README helps contributors and those unfamiliar with Travis CI to track down the status page easier. It also allows for easy on-the-fly viewing of the status of the repo (passing, failing, errored).

- [x] Add Markdown badge to the top of all READMEs for repos that are tested with Travis CI.

**Comment by mlangbehn** [comment]
We should do this with every repo using Travis CI.
