### ISSUE TITLE
Markdown linting

### ISSUE THREAD

**Issue by mlangbehn** [BonnyCI/docs#32]
Our current Markdown linter ([textlint](https://textlint.github.io/)), may not be actually checking Markdown syntax.

As such, we need to:
1. Verify textlint is checking Markdown syntax
2. If it isn't, investigate other options
    - [markdownlint](https://github.com/DavidAnson/markdownlint)
        -More specifically, [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli)
    - [mdl](https://github.com/mivok/markdownlint)
    - [mdlint](https://www.npmjs.com/package/mdlint)
    - [Other options](https://www.google.com/search?q=markdown+syntax+lint)?

If we need to look at a new option, it must:
- [x] Lint [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/) syntax
- [x] Be configurable
  - [x] Enable/disable specific rules

**Comment by mlangbehn** [comment]
Working on this in https://github.com/mlangbehn/lore/tree/add_markdownlint-cli

**Comment by eggshell** [comment]
I've used markdownlint with some success in the past, so I vote we move to that and bring the repo up to snuff. I'm fine with keeping the textlint stuff present since others find value in its feedback.

**Comment by mlangbehn** [comment]
Agreed. I'll knock that out tomorrow.
